### ISSUE TITLE
Multi-word variable names not supported

### ISSUE THREAD

**Issue by zhuowei** [wolfgang42/rockstar-js#2]
https://github.com/wolfgang42/rockstar#poetic-number-literals states that multi-word variables should be supported as long as each word begins with a capital letter.

Source:

```
Sweet Lucy was a dancer
```

Output:

```
$ yarn run transpile multiword.rock 
yarn run v1.6.0
$ node ./src/rockstar.js multiword.rock
{ SyntaxError: Expected " ", "\t", "is", or "takes" but "L" found.
    at peg$buildStructuredError (rockstar-js/src/rockstar-parser.js:491:12)
    at Object.peg$parse [as parse] (rockstar-js/src/rockstar-parser.js:2987:11)
    at compile (rockstar-js/src/rockstar.js:73:28)
    at <anonymous>
  message: 'Expected " ", "\\t", "is", or "takes" but "L" found.',
  expected: 
   [ { type: 'literal', text: ' ', ignoreCase: false },
     { type: 'literal', text: '\t', ignoreCase: false },
     { type: 'literal', text: 'takes', ignoreCase: false },
     { type: 'literal', text: ' ', ignoreCase: false },
     { type: 'literal', text: '\t', ignoreCase: false },
     { type: 'literal', text: 'is', ignoreCase: false } ],
  found: 'L',
  location: 
   { start: { offset: 6, line: 1, column: 7 },
     end: { offset: 7, line: 1, column: 8 } },
  name: 'SyntaxError' }
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```
It seems the parser [doesn't support spaces in proper variables](https://github.com/wolfgang42/rockstar-js/blob/master/src/rockstar-parser.peg#L9).

**Comment by wolfgang42** [comment]
Closed by e6b2fccd546ab42f1e434c0874a0de9457f1dc40. I had this working yesterday and then fell asleep before I pushed. :smile:
