### ISSUE TITLE
'Listen to' doesn't work

### ISSUE THREAD

**Issue by lewisdonovan** [wolfgang42/rockstar-js#5]
I can't get `Listen to` to work. Even something as simple as:
```
Listen to the words
Say the words
```
Still throws the following error:

```
[ 'Listen', [ ' ' ], 'to', [ ' ' ], { t: 'Variable', n: 'words' } ]
Error: Unknown statement type: undefined
    at expr (path/to/rockstar-js/src/rockstar.js:51:9)
    at Array.map (<anonymous>)
    at compile (path/to/rockstar-js/src/rockstar.js:76:17)
    at <anonymous>
error Command failed with exit code 1.
```

**Comment by wolfgang42** [comment]
`Listen to` is currently unimplemented; it's on my list of things to get working soon.

**Comment by lewisdonovan** [comment]
I've pulled the latest version of the repo and tried to transpile the example in 'listen.rock' and I get the following error:

```
[ 'Listen', [ ' ' ], 'to', [ ' ' ], { t: 'Variable', n: 'voice' } ]
Error: Unknown statement type: undefined
    at expr (/Users/dono023/Desktop/rockstar/rockstar-js/src/rockstar.js:77:9)
    at Array.map (<anonymous>)
    at compile (/Users/dono023/Desktop/rockstar/rockstar-js/src/rockstar.js:129:14)
    at <anonymous>
```

**EDIT**: Ignore this, my npm install was borked. Now working.
